apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: "1.10.3"
      helm:
        valueFiles:
          - $values/kubernetes/apps/tracing/tempo/values.yaml
    - repoURL: https://github.com/slydien/proxmox-k8s
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
